import { Anime } from '../types/anime';

export const GENRES_LIST = [
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Fantasy',
  'Horror',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Shounen',
  'Slice of Life',
  'Sports',
  'Supernatural',
  'Thriller',
];

export const DEMO_ANIME: Anime[] = [
  {
    id: 'attack-on-titan',
    title: 'Attack on Titan',
    japaneseTitle: 'Shingeki no Kyojin',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    rating: 9.1,
    year: 2013,
    genres: ['Action', 'Drama', 'Fantasy', 'Mystery', 'Shounen'],
    episodesCount: 89,
    status: 'Completed',
    type: 'TV',
    studio: 'MAPPA / Wit Studio',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    featuredInHero: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `aot-ep-${i + 1}`,
      number: i + 1,
      title: [
        'To You, 2,000 Years in the Future',
        'That Day: The Fall of Shiganshina',
        'A Dim Light Amid Despair',
        'The Night of the Disbandment Ceremony',
        'First Battle: The Struggle for Trost',
        'The World the Girl Saw',
        'Small Blade: The Struggle for Trost 3',
        'Hearing the Heartbeat',
        'Whereabouts of His Left Arm',
        'Response: The Struggle for Trost 6',
        'Idol: The Struggle for Trost 7',
        'Wound: The Struggle for Trost 8'
      ][i] || `Episode ${i + 1}`,
      thumbnail: `https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=500&auto=format&fit=crop`,
      duration: '24m',
      airDate: '2021-01-10',
      description: 'Eren and his comrades face unprecedented titan threats in an explosive turn of events.'
    })),
    characters: [
      { id: '1', name: 'Eren Yeager', role: 'Main', image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=300&auto=format&fit=crop', voiceActor: 'Yuki Kaji' },
      { id: '2', name: 'Mikasa Ackerman', role: 'Main', image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=300&auto=format&fit=crop', voiceActor: 'Yui Ishikawa' },
      { id: '3', name: 'Levi Ackerman', role: 'Main', image: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=300&auto=format&fit=crop', voiceActor: 'Hiroshi Kamiya' },
    ]
  },
  {
    id: 'demon-slayer',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    japaneseTitle: 'Kimetsu no Yaiba',
    description: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon herself. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.',
    poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    rating: 8.9,
    year: 2019,
    genres: ['Action', 'Fantasy', 'Supernatural', 'Shounen'],
    episodesCount: 55,
    status: 'Ongoing',
    type: 'TV',
    studio: 'ufotable',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    featuredInHero: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ds-ep-${i + 1}`,
      number: i + 1,
      title: `Demon Slayer Arc Episode ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=500&auto=format&fit=crop',
      duration: '24m',
      airDate: '2023-04-09'
    }))
  },
  {
    id: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    japaneseTitle: 'Jujutsu Kaisen',
    description: 'A boy swallowed a cursed talisman - the finger of a demon - and became cursed himself. He enters a shaman school to be able to locate the demon\'s other body parts and thus exorcise himself.',
    poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1600&auto=format&fit=crop',
    rating: 8.7,
    year: 2020,
    genres: ['Action', 'Fantasy', 'Supernatural', 'Shounen'],
    episodesCount: 47,
    status: 'Ongoing',
    type: 'TV',
    studio: 'MAPPA',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: true,
    featuredInHero: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `jjk-ep-${i + 1}`,
      number: i + 1,
      title: `Shibuya Incident Episode ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  },
  {
    id: 'solo-leveling',
    title: 'Solo Leveling',
    japaneseTitle: 'Ore dake Level Up na Ken',
    description: 'In a world where hunters, humans who possess magical abilities, must battle deadly monsters to protect the human race, a notoriously weak hunter named Sung Jinwoo finds himself in a seamless struggle for survival.',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1600&auto=format&fit=crop',
    rating: 8.8,
    year: 2024,
    genres: ['Action', 'Adventure', 'Fantasy', 'Supernatural'],
    episodesCount: 12,
    status: 'Ongoing',
    type: 'TV',
    studio: 'A-1 Pictures',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    featuredInHero: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `sl-ep-${i + 1}`,
      number: i + 1,
      title: `I\'m Used to It Episode ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  },
  {
    id: 'one-piece',
    title: 'One Piece',
    japaneseTitle: 'One Piece',
    description: 'Monkey D. Luffy sets off on an epic sea voyage with his Straw Hat Pirates to find the legendary treasure "One Piece" and become the King of the Pirates.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1600&auto=format&fit=crop',
    rating: 9.0,
    year: 1999,
    genres: ['Action', 'Adventure', 'Comedy', 'Fantasy', 'Shounen'],
    episodesCount: 1100,
    status: 'Ongoing',
    type: 'TV',
    studio: 'Toei Animation',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `op-ep-${1080 + i}`,
      number: 1080 + i,
      title: `Egghead Island Arc Ep ${1080 + i}`,
      thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  },
  {
    id: 'frieren',
    title: 'Frieren: Beyond Journey\'s End',
    japaneseTitle: 'Sousou no Frieren',
    description: 'Elven mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren will long outlive the rest of her former party, embarking on a new journey to discover humanity.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1600&auto=format&fit=crop',
    rating: 9.3,
    year: 2023,
    genres: ['Adventure', 'Drama', 'Fantasy', 'Slice of Life'],
    episodesCount: 28,
    status: 'Completed',
    type: 'TV',
    studio: 'Madhouse',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `frieren-ep-${i + 1}`,
      number: i + 1,
      title: `The Journey Continues Ep ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  },
  {
    id: 'chainsaw-man',
    title: 'Chainsaw Man',
    japaneseTitle: 'Chainsaw Man',
    description: 'Following a betrayal, a young man left for dead is revived as a powerful devil-human hybrid by merging with his pet devil dog Pochita.',
    poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1600&auto=format&fit=crop',
    rating: 8.5,
    year: 2022,
    genres: ['Action', 'Horror', 'Supernatural', 'Shounen'],
    episodesCount: 12,
    status: 'Completed',
    type: 'TV',
    studio: 'MAPPA',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `csm-ep-${i + 1}`,
      number: i + 1,
      title: `Chainsaw vs Devil Ep ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  },
  {
    id: 'naruto-shippuden',
    title: 'Naruto Shippuden',
    japaneseTitle: 'Naruto: Shippuuden',
    description: 'Naruto Uzumaki returns to the Hidden Leaf Village after two and a half years of intense training, determined to save his friend Sasuke Uchiha from Orochimaru and become Hokage.',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    rating: 8.7,
    year: 2007,
    genres: ['Action', 'Adventure', 'Fantasy', 'Shounen'],
    episodesCount: 500,
    status: 'Completed',
    type: 'TV',
    studio: 'Studio Pierrot',
    duration: '23m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `naruto-ep-${i + 1}`,
      number: i + 1,
      title: `Homecoming Ep ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=500&auto=format&fit=crop',
      duration: '23m'
    }))
  },
  {
    id: 'my-hero-academia',
    title: 'My Hero Academia',
    japaneseTitle: 'Boku no Hero Academia',
    description: 'A superhero-loving boy without powers is determined to enroll in a prestigious hero academy and learn what it truly means to be a hero.',
    poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    rating: 8.4,
    year: 2016,
    genres: ['Action', 'Comedy', 'Shounen', 'Supernatural'],
    episodesCount: 138,
    status: 'Ongoing',
    type: 'TV',
    studio: 'Bones',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `mha-ep-${i + 1}`,
      number: i + 1,
      title: `Izuku Midoriya: Origin Ep ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  },
  {
    id: 'death-note',
    title: 'Death Note',
    japaneseTitle: 'Death Note',
    description: 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written in it.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1600&auto=format&fit=crop',
    rating: 9.0,
    year: 2006,
    genres: ['Mystery', 'Supernatural', 'Thriller', 'Shounen'],
    episodesCount: 37,
    status: 'Completed',
    type: 'TV',
    studio: 'Madhouse',
    duration: '23m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `dn-ep-${i + 1}`,
      number: i + 1,
      title: `Rebirth Ep ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=500&auto=format&fit=crop',
      duration: '23m'
    }))
  },
  {
    id: 'bleach-tybw',
    title: 'Bleach: Thousand-Year Blood War',
    japaneseTitle: 'Bleach: Sennen Kessen-hen',
    description: 'The peace is suddenly broken when warning sirens ring through the Soul Society. Residents there are disappearing without a trace and nobody knows who is behind it.',
    poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1600&auto=format&fit=crop',
    rating: 9.0,
    year: 2022,
    genres: ['Action', 'Adventure', 'Supernatural', 'Shounen'],
    episodesCount: 26,
    status: 'Ongoing',
    type: 'TV',
    studio: 'Studio Pierrot',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `bleach-ep-${i + 1}`,
      number: i + 1,
      title: `THE BLOOD WAR Ep ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  },
  {
    id: 'one-punch-man',
    title: 'One Punch Man',
    japaneseTitle: 'One Punch Man',
    description: 'The story of Saitama, a superhero who can defeat any opponent with a single punch but seeks to find a worthy opponent after growing bored by a lack of challenge.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    rating: 8.7,
    year: 2015,
    genres: ['Action', 'Comedy', 'Sci-Fi', 'Supernatural'],
    episodesCount: 24,
    status: 'Completed',
    type: 'TV',
    studio: 'Madhouse / J.C.Staff',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `opm-ep-${i + 1}`,
      number: i + 1,
      title: `The Strongest Man Ep ${i + 1}`,
      thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=500&auto=format&fit=crop',
      duration: '24m'
    }))
  }
];
