import { Anime } from '../types/anime';
import { ANIME_IMAGE_MAP } from '../services/animeImageService';

export const GENRES_LIST = [
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Fantasy',
  'Horror',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Sports',
  'Supernatural',
  'Thriller',
  'Historical',
  'Music',
  'School',
  'Martial Arts',
];

export const DEMO_ANIME: Anime[] = [
  {
    id: 'attack-on-titan',
    slug: 'attack-on-titan',
    title: 'Attack on Titan',
    japaneseTitle: 'Shingeki no Kyojin',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    poster: ANIME_IMAGE_MAP['attack-on-titan'].poster,
    banner: ANIME_IMAGE_MAP['attack-on-titan'].banner,
    rating: 9.1,
    year: 2013,
    genres: ['Action', 'Drama', 'Fantasy', 'Mystery'],
    episodesCount: 89,
    status: 'Completed',
    type: 'TV',
    studio: 'MAPPA / Wit Studio',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    featuredInHero: true,
    episodes: Array.from({ length: 24 }, (_, i) => ({
      id: `aot-ep-${i + 1}`,
      number: i + 1,
      title: [
        'To You, 2,000 Years in the Future',
        'That Day: The Fall of Shiganshina',
        'A Dim Light Amid Despair',
        'The Night of the Disbandment Ceremony',
        'First Battle: The Struggle for Trost',
        'The World the Girl Saw',
        'Small Blade: The Struggle for Trost 3',
        'Hearing the Heartbeat',
        'Whereabouts of His Left Arm',
        'Response: The Struggle for Trost 6',
        'Idol: The Struggle for Trost 7',
        'Wound: The Struggle for Trost 8',
        'Primal Desire',
        'Can\'t Look Into His Eyes Yet',
        'Special Operations Squad',
        'What Needs to be Done Now',
        'Female Titan',
        'Forest of Giant Trees',
        'Bite: Struggle for Trost 10',
        'Erwin Smith',
        'Crushing Blow',
        'The Defeated',
        'Smile: Assault on Stohess',
        'Mercy: Assault on Stohess 2'
      ][i] || `Episode ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['attack-on-titan'].banner,
      duration: '24m',
      airDate: '2013-04-07',
      description: 'Eren and his comrades face unprecedented titan threats in an explosive turn of events.'
    })),
    characters: [
      { id: '1', name: 'Eren Yeager', role: 'Main', image: ANIME_IMAGE_MAP['attack-on-titan'].poster, voiceActor: 'Yuki Kaji' },
      { id: '2', name: 'Mikasa Ackerman', role: 'Main', image: ANIME_IMAGE_MAP['attack-on-titan'].poster, voiceActor: 'Yui Ishikawa' },
      { id: '3', name: 'Levi Ackerman', role: 'Main', image: ANIME_IMAGE_MAP['attack-on-titan'].poster, voiceActor: 'Hiroshi Kamiya' }
    ]
  },
  {
    id: 'demon-slayer',
    slug: 'demon-slayer',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    japaneseTitle: 'Kimetsu no Yaiba',
    description: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon herself. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.',
    poster: ANIME_IMAGE_MAP['demon-slayer'].poster,
    banner: ANIME_IMAGE_MAP['demon-slayer'].banner,
    rating: 8.9,
    year: 2019,
    genres: ['Action', 'Fantasy', 'Supernatural', 'Historical'],
    episodesCount: 55,
    status: 'Ongoing',
    type: 'TV',
    studio: 'ufotable',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    featuredInHero: true,
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: `ds-ep-${i + 1}`,
      number: i + 1,
      title: `Demon Slayer Arc Episode ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['demon-slayer'].banner,
      duration: '24m',
      airDate: '2019-04-06',
      description: 'Tanjiro undergoes perilous training to master Breathing Techniques.'
    }))
  },
  {
    id: 'jujutsu-kaisen',
    slug: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    japaneseTitle: 'Jujutsu Kaisen',
    description: 'A boy swallowed a cursed talisman - the finger of a demon - and became cursed himself. He enters a shaman school to be able to locate the demon\'s other body parts and thus exorcise himself.',
    poster: ANIME_IMAGE_MAP['jujutsu-kaisen'].poster,
    banner: ANIME_IMAGE_MAP['jujutsu-kaisen'].banner,
    rating: 8.7,
    year: 2020,
    genres: ['Action', 'Fantasy', 'Supernatural', 'School'],
    episodesCount: 47,
    status: 'Ongoing',
    type: 'TV',
    studio: 'MAPPA',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: true,
    featuredInHero: true,
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: `jjk-ep-${i + 1}`,
      number: i + 1,
      title: `Shibuya Incident Episode ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['jujutsu-kaisen'].banner,
      duration: '24m',
      description: 'The jujutsu sorcerers gather in Tokyo as special grade curses execute a colossal barrier trap.'
    }))
  },
  {
    id: 'solo-leveling',
    slug: 'solo-leveling',
    title: 'Solo Leveling',
    japaneseTitle: 'Ore dake Level Up na Ken',
    description: 'In a world where hunters, humans who possess magical abilities, must battle deadly monsters to protect the human race, a notoriously weak hunter named Sung Jinwoo finds himself in a struggle for survival.',
    poster: ANIME_IMAGE_MAP['solo-leveling'].poster,
    banner: ANIME_IMAGE_MAP['solo-leveling'].banner,
    rating: 8.8,
    year: 2024,
    genres: ['Action', 'Adventure', 'Fantasy', 'Supernatural'],
    episodesCount: 12,
    status: 'Ongoing',
    type: 'TV',
    studio: 'A-1 Pictures',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    featuredInHero: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `sl-ep-${i + 1}`,
      number: i + 1,
      title: `System Notification Episode ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['solo-leveling'].banner,
      duration: '24m',
      description: 'Sung Jinwoo unlocks the mysterious quest log interface and begins daily stat grinding.'
    }))
  },
  {
    id: 'one-piece',
    slug: 'one-piece',
    title: 'One Piece',
    japaneseTitle: 'One Piece',
    description: 'Monkey D. Luffy sets off on an epic sea voyage with his Straw Hat Pirates to find the legendary treasure "One Piece" and become the King of the Pirates.',
    poster: ANIME_IMAGE_MAP['one-piece'].poster,
    banner: ANIME_IMAGE_MAP['one-piece'].banner,
    rating: 9.0,
    year: 1999,
    genres: ['Action', 'Adventure', 'Comedy', 'Fantasy'],
    episodesCount: 1100,
    status: 'Ongoing',
    type: 'TV',
    studio: 'Toei Animation',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: `op-ep-${1080 + i}`,
      number: 1080 + i,
      title: `Egghead Island Climax Ep ${1080 + i}`,
      thumbnail: ANIME_IMAGE_MAP['one-piece'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'frieren',
    slug: 'frieren',
    title: 'Frieren: Beyond Journey\'s End',
    japaneseTitle: 'Sousou no Frieren',
    description: 'Elven mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren will long outlive the rest of her former party, embarking on a new journey to discover humanity.',
    poster: ANIME_IMAGE_MAP['frieren'].poster,
    banner: ANIME_IMAGE_MAP['frieren'].banner,
    rating: 9.3,
    year: 2023,
    genres: ['Adventure', 'Drama', 'Fantasy'],
    episodesCount: 28,
    status: 'Completed',
    type: 'TV',
    studio: 'Madhouse',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: `frieren-ep-${i + 1}`,
      number: i + 1,
      title: `The Journey Continues Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['frieren'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'chainsaw-man',
    slug: 'chainsaw-man',
    title: 'Chainsaw Man',
    japaneseTitle: 'Chainsaw Man',
    description: 'Following a betrayal, a young man left for dead is revived as a powerful devil-human hybrid by merging with his pet devil dog Pochita.',
    poster: ANIME_IMAGE_MAP['chainsaw-man'].poster,
    banner: ANIME_IMAGE_MAP['chainsaw-man'].banner,
    rating: 8.5,
    year: 2022,
    genres: ['Action', 'Horror', 'Supernatural', 'Thriller'],
    episodesCount: 12,
    status: 'Completed',
    type: 'TV',
    studio: 'MAPPA',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `csm-ep-${i + 1}`,
      number: i + 1,
      title: `Chainsaw vs Devil Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['chainsaw-man'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'naruto-shippuden',
    slug: 'naruto-shippuden',
    title: 'Naruto Shippuden',
    japaneseTitle: 'Naruto: Shippuuden',
    description: 'Naruto Uzumaki returns to the Hidden Leaf Village after two and a half years of intense training, determined to save his friend Sasuke Uchiha from Orochimaru and become Hokage.',
    poster: ANIME_IMAGE_MAP['naruto-shippuden'].poster,
    banner: ANIME_IMAGE_MAP['naruto-shippuden'].banner,
    rating: 8.7,
    year: 2007,
    genres: ['Action', 'Adventure', 'Fantasy', 'Martial Arts'],
    episodesCount: 500,
    status: 'Completed',
    type: 'TV',
    studio: 'Studio Pierrot',
    duration: '23m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 15 }, (_, i) => ({
      id: `naruto-ep-${i + 1}`,
      number: i + 1,
      title: `Homecoming Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['naruto-shippuden'].banner,
      duration: '23m'
    }))
  },
  {
    id: 'my-hero-academia',
    slug: 'my-hero-academia',
    title: 'My Hero Academia',
    japaneseTitle: 'Boku no Hero Academia',
    description: 'A superhero-loving boy without powers is determined to enroll in a prestigious hero academy and learn what it truly means to be a hero.',
    poster: ANIME_IMAGE_MAP['my-hero-academia'].poster,
    banner: ANIME_IMAGE_MAP['my-hero-academia'].banner,
    rating: 8.4,
    year: 2016,
    genres: ['Action', 'Comedy', 'School', 'Supernatural'],
    episodesCount: 138,
    status: 'Ongoing',
    type: 'TV',
    studio: 'Bones',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `mha-ep-${i + 1}`,
      number: i + 1,
      title: `Izuku Midoriya: Origin Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['my-hero-academia'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'death-note',
    slug: 'death-note',
    title: 'Death Note',
    japaneseTitle: 'Death Note',
    description: 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written in it.',
    poster: ANIME_IMAGE_MAP['death-note'].poster,
    banner: ANIME_IMAGE_MAP['death-note'].banner,
    rating: 9.0,
    year: 2006,
    genres: ['Mystery', 'Supernatural', 'Thriller'],
    episodesCount: 37,
    status: 'Completed',
    type: 'TV',
    studio: 'Madhouse',
    duration: '23m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `dn-ep-${i + 1}`,
      number: i + 1,
      title: `Rebirth Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['death-note'].banner,
      duration: '23m'
    }))
  },
  {
    id: 'bleach-tybw',
    slug: 'bleach-tybw',
    title: 'Bleach: Thousand-Year Blood War',
    japaneseTitle: 'Bleach: Sennen Kessen-hen',
    description: 'The peace is suddenly broken when warning sirens ring through the Soul Society. Residents there are disappearing without a trace and nobody knows who is behind it.',
    poster: ANIME_IMAGE_MAP['bleach-tybw'].poster,
    banner: ANIME_IMAGE_MAP['bleach-tybw'].banner,
    rating: 9.0,
    year: 2022,
    genres: ['Action', 'Adventure', 'Supernatural', 'Martial Arts'],
    episodesCount: 26,
    status: 'Ongoing',
    type: 'TV',
    studio: 'Studio Pierrot',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `bleach-ep-${i + 1}`,
      number: i + 1,
      title: `THE BLOOD WAR Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['bleach-tybw'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'one-punch-man',
    slug: 'one-punch-man',
    title: 'One Punch Man',
    japaneseTitle: 'One Punch Man',
    description: 'The story of Saitama, a superhero who can defeat any opponent with a single punch but seeks to find a worthy opponent after growing bored by a lack of challenge.',
    poster: ANIME_IMAGE_MAP['one-punch-man'].poster,
    banner: ANIME_IMAGE_MAP['one-punch-man'].banner,
    rating: 8.7,
    year: 2015,
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    episodesCount: 24,
    status: 'Completed',
    type: 'TV',
    studio: 'Madhouse / J.C.Staff',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `opm-ep-${i + 1}`,
      number: i + 1,
      title: `The Strongest Man Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['one-punch-man'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'your-name',
    slug: 'your-name',
    title: 'Your Name',
    japaneseTitle: 'Kimi no Na wa',
    description: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    poster: ANIME_IMAGE_MAP['your-name'].poster,
    banner: ANIME_IMAGE_MAP['your-name'].banner,
    rating: 8.9,
    year: 2016,
    genres: ['Romance', 'Drama', 'Supernatural', 'School'],
    episodesCount: 1,
    status: 'Completed',
    type: 'Movie',
    studio: 'CoMix Wave Films',
    duration: '1h 46m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: [
      {
        id: 'yn-movie-1',
        number: 1,
        title: 'Your Name (Full Movie)',
        thumbnail: ANIME_IMAGE_MAP['your-name'].banner,
        duration: '106m',
        description: 'Mitsuha and Taki switch bodies across mountain shrines and Tokyo cityscapes.'
      }
    ]
  },
  {
    id: 'spirited-away',
    slug: 'spirited-away',
    title: 'Spirited Away',
    japaneseTitle: 'Sen to Chihiro no Kamikakushi',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.',
    poster: ANIME_IMAGE_MAP['spirited-away'].poster,
    banner: ANIME_IMAGE_MAP['spirited-away'].banner,
    rating: 8.6,
    year: 2001,
    genres: ['Adventure', 'Fantasy', 'Supernatural'],
    episodesCount: 1,
    status: 'Completed',
    type: 'Movie',
    studio: 'Studio Ghibli',
    duration: '2h 5m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: [
      {
        id: 'sa-movie-1',
        number: 1,
        title: 'Spirited Away (Full Feature)',
        thumbnail: ANIME_IMAGE_MAP['spirited-away'].banner,
        duration: '125m'
      }
    ]
  },
  {
    id: 'haikyuu',
    slug: 'haikyuu',
    title: 'Haikyu!!',
    japaneseTitle: 'Haikyuu!!',
    description: 'Determined to be like the legendary volleyball player known as the "Little Giant," Shouyou Hinata revives the volleyball club at his middle school.',
    poster: ANIME_IMAGE_MAP['haikyuu'].poster,
    banner: ANIME_IMAGE_MAP['haikyuu'].banner,
    rating: 8.7,
    year: 2014,
    genres: ['Sports', 'Comedy', 'Drama', 'School'],
    episodesCount: 85,
    status: 'Completed',
    type: 'TV',
    studio: 'Production I.G',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `haikyuu-ep-${i + 1}`,
      number: i + 1,
      title: `Tournament Rally Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['haikyuu'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'blue-lock',
    slug: 'blue-lock',
    title: 'Blue Lock',
    japaneseTitle: 'Blue Lock',
    description: 'After a disastrous defeat at the 2018 World Cup, Japan\'s football team struggles to regroup. The Union hires enigmatic coach Jinpachi Ego to build the ultimate selfish striker.',
    poster: ANIME_IMAGE_MAP['blue-lock'].poster,
    banner: ANIME_IMAGE_MAP['blue-lock'].banner,
    rating: 8.3,
    year: 2022,
    genres: ['Sports', 'Action', 'Thriller', 'School'],
    episodesCount: 24,
    status: 'Ongoing',
    type: 'TV',
    studio: '8bit',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `bl-ep-${i + 1}`,
      number: i + 1,
      title: `Egoist Selection Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['blue-lock'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'cyberpunk-edgerunners',
    slug: 'cyberpunk-edgerunners',
    title: 'Cyberpunk: Edgerunners',
    japaneseTitle: 'Cyberpunk: Edgerunners',
    description: 'A street kid trying to survive in a technology and body modification-obsessed city of the future chooses to stay alive by becoming an edgerunner mercenary.',
    poster: ANIME_IMAGE_MAP['cyberpunk-edgerunners'].poster,
    banner: ANIME_IMAGE_MAP['cyberpunk-edgerunners'].banner,
    rating: 8.6,
    year: 2022,
    genres: ['Action', 'Sci-Fi', 'Drama', 'Thriller'],
    episodesCount: 10,
    status: 'Completed',
    type: 'OVA',
    studio: 'Trigger',
    duration: '25m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: `cpe-ep-${i + 1}`,
      number: i + 1,
      title: `Night City Cyberware Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['cyberpunk-edgerunners'].banner,
      duration: '25m'
    }))
  },
  {
    id: 'kaguya-sama',
    slug: 'kaguya-sama',
    title: 'Kaguya-sama: Love is War',
    japaneseTitle: 'Kaguya-sama wa Kokurasetai',
    description: 'The prideful elite student council president and vice president engage in ruthless mental games to force the other to confess their love first.',
    poster: ANIME_IMAGE_MAP['kaguya-sama'].poster,
    banner: ANIME_IMAGE_MAP['kaguya-sama'].banner,
    rating: 8.8,
    year: 2019,
    genres: ['Comedy', 'Romance', 'School'],
    episodesCount: 37,
    status: 'Completed',
    type: 'TV',
    studio: 'A-1 Pictures',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `kaguya-ep-${i + 1}`,
      number: i + 1,
      title: `Mind Games Battle Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['kaguya-sama'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'tokyo-ghoul',
    slug: 'tokyo-ghoul',
    title: 'Tokyo Ghoul',
    japaneseTitle: 'Tokyo Ghoul',
    description: 'A Tokyo college student is attacked by a ghoul, a superpowered human who feeds on human flesh. He survives, but has become part ghoul and a fugitive on the run.',
    poster: ANIME_IMAGE_MAP['tokyo-ghoul'].poster,
    banner: ANIME_IMAGE_MAP['tokyo-ghoul'].banner,
    rating: 7.8,
    year: 2014,
    genres: ['Action', 'Horror', 'Mystery', 'Supernatural', 'Thriller'],
    episodesCount: 24,
    status: 'Completed',
    type: 'TV',
    studio: 'Studio Pierrot',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `tg-ep-${i + 1}`,
      number: i + 1,
      title: `Tragedy Awakening Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['tokyo-ghoul'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'vinland-saga',
    slug: 'vinland-saga',
    title: 'Vinland Saga',
    japaneseTitle: 'Vinland Saga',
    description: 'Thorfinn pursues a journey with his father\'s killer in order to take revenge and end his life in a duel, while an epic war for the crown of England consumes Europe.',
    poster: ANIME_IMAGE_MAP['vinland-saga'].poster,
    banner: ANIME_IMAGE_MAP['vinland-saga'].banner,
    rating: 8.8,
    year: 2019,
    genres: ['Action', 'Adventure', 'Drama', 'Historical'],
    episodesCount: 48,
    status: 'Completed',
    type: 'TV',
    studio: 'MAPPA / Wit Studio',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `vs-ep-${i + 1}`,
      number: i + 1,
      title: `Viking Raid Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['vinland-saga'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'steins-gate',
    slug: 'steins-gate',
    title: 'Steins;Gate',
    japaneseTitle: 'Steins;Gate',
    description: 'After discovering time travel, a self-proclaimed mad scientist and his eccentric friends must find a way to prevent a dystopian future caused by a secretive organization.',
    poster: ANIME_IMAGE_MAP['steins-gate'].poster,
    banner: ANIME_IMAGE_MAP['steins-gate'].banner,
    rating: 9.1,
    year: 2011,
    genres: ['Sci-Fi', 'Thriller', 'Mystery'],
    episodesCount: 24,
    status: 'Completed',
    type: 'TV',
    studio: 'White Fox',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `sg-ep-${i + 1}`,
      number: i + 1,
      title: `D-Mail Paradox Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['steins-gate'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'hunter-x-hunter',
    slug: 'hunter-x-hunter',
    title: 'Hunter x Hunter',
    japaneseTitle: 'Hunter x Hunter',
    description: 'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks out his father who left him when he was young.',
    poster: ANIME_IMAGE_MAP['hunter-x-hunter'].poster,
    banner: ANIME_IMAGE_MAP['hunter-x-hunter'].banner,
    rating: 9.0,
    year: 2011,
    genres: ['Action', 'Adventure', 'Fantasy'],
    episodesCount: 148,
    status: 'Completed',
    type: 'TV',
    studio: 'Madhouse',
    duration: '23m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `hxh-ep-${i + 1}`,
      number: i + 1,
      title: `Hunter Exam Phase Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['hunter-x-hunter'].banner,
      duration: '23m'
    }))
  },
  {
    id: 'spy-x-family',
    slug: 'spy-x-family',
    title: 'Spy x Family',
    japaneseTitle: 'Spy x Family',
    description: 'A spy on an undercover mission marries an assassin and adopts a telepathic girl, all three pretending to be an ordinary family while hiding their true identities from each other.',
    poster: ANIME_IMAGE_MAP['spy-x-family'].poster,
    banner: ANIME_IMAGE_MAP['spy-x-family'].banner,
    rating: 8.5,
    year: 2022,
    genres: ['Action', 'Comedy', 'Slice of Life'],
    episodesCount: 37,
    status: 'Ongoing',
    type: 'TV',
    studio: 'WIT Studio / CloverWorks',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `sxf-ep-${i + 1}`,
      number: i + 1,
      title: `Operation Strix Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['spy-x-family'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'mob-psycho-100',
    slug: 'mob-psycho-100',
    title: 'Mob Psycho 100',
    japaneseTitle: 'Mob Psycho 100',
    description: 'A psychic middle school boy tries to live a normal life and keep his growing powers under control, constantly attracting trouble.',
    poster: ANIME_IMAGE_MAP['mob-psycho-100'].poster,
    banner: ANIME_IMAGE_MAP['mob-psycho-100'].banner,
    rating: 8.6,
    year: 2016,
    genres: ['Action', 'Comedy', 'Supernatural', 'School'],
    episodesCount: 37,
    status: 'Completed',
    type: 'TV',
    studio: 'Bones',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `mp100-ep-${i + 1}`,
      number: i + 1,
      title: `100 Percent Burst Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['mob-psycho-100'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'bocchi-the-rock',
    slug: 'bocchi-the-rock',
    title: 'Bocchi the Rock!',
    japaneseTitle: 'Bocchi the Rock!',
    description: 'A socially anxious high school girl who plays guitar joins an indie rock band and discovers friendship through music.',
    poster: ANIME_IMAGE_MAP['bocchi-the-rock'].poster,
    banner: ANIME_IMAGE_MAP['bocchi-the-rock'].banner,
    rating: 8.8,
    year: 2022,
    genres: ['Music', 'Comedy', 'School'],
    episodesCount: 12,
    status: 'Completed',
    type: 'TV',
    studio: 'CloverWorks',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `btr-ep-${i + 1}`,
      number: i + 1,
      title: `Lonely Rolling Band Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['bocchi-the-rock'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'fate-stay-night-unlimited-blade-works',
    slug: 'fate-stay-night-unlimited-blade-works',
    title: 'Fate/stay night: Unlimited Blade Works',
    japaneseTitle: 'Fate/stay night [Unlimited Blade Works]',
    description: 'Seven mages summon legendary heroic spirits to fight for the almighty Holy Grail in a deadly magical battle royale.',
    poster: ANIME_IMAGE_MAP['fate-stay-night-unlimited-blade-works'].poster,
    banner: ANIME_IMAGE_MAP['fate-stay-night-unlimited-blade-works'].banner,
    rating: 8.2,
    year: 2014,
    genres: ['Action', 'Fantasy', 'Supernatural'],
    episodesCount: 26,
    status: 'Completed',
    type: 'TV',
    studio: 'ufotable',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `fate-ep-${i + 1}`,
      number: i + 1,
      title: `Holy Grail War Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['fate-stay-night-unlimited-blade-works'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'cowboy-bebop',
    slug: 'cowboy-bebop',
    title: 'Cowboy Bebop',
    japaneseTitle: 'Cowboy Bebop',
    description: 'The futuristic misadventures and tragedies of an easygoing bounty hunter and his partners wandering space in search of criminal rewards.',
    poster: ANIME_IMAGE_MAP['cowboy-bebop'].poster,
    banner: ANIME_IMAGE_MAP['cowboy-bebop'].banner,
    rating: 8.9,
    year: 1998,
    genres: ['Sci-Fi', 'Action', 'Drama'],
    episodesCount: 26,
    status: 'Completed',
    type: 'TV',
    studio: 'Sunrise',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `cb-ep-${i + 1}`,
      number: i + 1,
      title: `Asteroid Blues Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['cowboy-bebop'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'fullmetal-alchemist-brotherhood',
    slug: 'fullmetal-alchemist-brotherhood',
    title: 'Fullmetal Alchemist: Brotherhood',
    japaneseTitle: 'Hagane no Renkinjutsushi',
    description: 'Two brothers search for the Philosopher\'s Stone after an attempt to revive their deceased mother goes horribly wrong.',
    poster: ANIME_IMAGE_MAP['fullmetal-alchemist-brotherhood'].poster,
    banner: ANIME_IMAGE_MAP['fullmetal-alchemist-brotherhood'].banner,
    rating: 9.1,
    year: 2009,
    genres: ['Action', 'Adventure', 'Fantasy', 'Drama'],
    episodesCount: 64,
    status: 'Completed',
    type: 'TV',
    studio: 'Bones',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 14 }, (_, i) => ({
      id: `fmab-ep-${i + 1}`,
      number: i + 1,
      title: `Alchemy Transmutation Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['fullmetal-alchemist-brotherhood'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'slam-dunk',
    slug: 'slam-dunk',
    title: 'Slam Dunk',
    japaneseTitle: 'Slam Dunk',
    description: 'Hanamichi Sakuragi is a delinquent with a long history of getting dumped. After enrolling at Shohoku High, Hanamichi becomes interested in a girl named Haruko who loves basketball.',
    poster: ANIME_IMAGE_MAP['slam-dunk'].poster,
    banner: ANIME_IMAGE_MAP['slam-dunk'].banner,
    rating: 8.5,
    year: 1993,
    genres: ['Sports', 'Comedy', 'School'],
    episodesCount: 101,
    status: 'Completed',
    type: 'TV',
    studio: 'Toei Animation',
    duration: '23m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: false,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `sd-ep-${i + 1}`,
      number: i + 1,
      title: `Shohoku Rebound Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['slam-dunk'].banner,
      duration: '23m'
    }))
  },
  {
    id: 'violet-evergarden',
    slug: 'violet-evergarden',
    title: 'Violet Evergarden',
    japaneseTitle: 'Violet Evergarden',
    description: 'In the aftermath of a great war, an ex-soldier child weapon works as an Auto Memory Doll ghostwriter to understand the final words told to her by her commanding officer.',
    poster: ANIME_IMAGE_MAP['violet-evergarden'].poster,
    banner: ANIME_IMAGE_MAP['violet-evergarden'].banner,
    rating: 8.7,
    year: 2018,
    genres: ['Drama', 'Fantasy', 'Romance'],
    episodesCount: 13,
    status: 'Completed',
    type: 'TV',
    studio: 'Kyoto Animation',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 13 }, (_, i) => ({
      id: `ve-ep-${i + 1}`,
      number: i + 1,
      title: `Auto Memory Doll Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['violet-evergarden'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'dandadan',
    slug: 'dandadan',
    title: 'Dandadan',
    japaneseTitle: 'Dandadan',
    description: 'A high school girl who believes in ghosts and a boy who believes in aliens make a wager that drags them both into terrifying paranormal encounters.',
    poster: ANIME_IMAGE_MAP['dandadan'].poster,
    banner: ANIME_IMAGE_MAP['dandadan'].banner,
    rating: 8.6,
    year: 2025,
    genres: ['Action', 'Comedy', 'Supernatural', 'Romance'],
    episodesCount: 12,
    status: 'Ongoing',
    type: 'TV',
    studio: 'Science SARU',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    isRecentlyAdded: true,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `ddd-ep-${i + 1}`,
      number: i + 1,
      title: `Occult & Alien Encounter Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['dandadan'].banner,
      duration: '24m'
    }))
  },
  {
    id: 'fate-grand-order-babylonia',
    slug: 'fate-grand-order-babylonia',
    title: 'Fate/Grand Order Absolute Demonic Front: Babylonia',
    japaneseTitle: 'Fate/Grand Order: Zettai Majuu Sensen Babylonia',
    description: 'Chaldea rayshifts into ancient Mesopotamia in 2650 BC to resolve the final singularity threatening human history.',
    poster: ANIME_IMAGE_MAP['fate-grand-order-babylonia'].poster,
    banner: ANIME_IMAGE_MAP['fate-grand-order-babylonia'].banner,
    rating: 7.9,
    year: 2019,
    genres: ['Action', 'Fantasy', 'Historical'],
    episodesCount: 21,
    status: 'Completed',
    type: 'TV',
    studio: 'CloverWorks',
    duration: '24m',
    isSubbed: true,
    isDubbed: true,
    isTrending: false,
    isPopular: false,
    isTopRated: false,
    isRecentlyAdded: false,
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `fgo-ep-${i + 1}`,
      number: i + 1,
      title: `Babylonia Singularity Ep ${i + 1}`,
      thumbnail: ANIME_IMAGE_MAP['fate-grand-order-babylonia'].banner,
      duration: '24m'
    }))
  }
];
